
/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener ///

package org.swiftjava.com_johnholdsworth;

@SuppressWarnings("JniMissingFunction")
public class SwiftHelloTest_TestListenerProxy implements com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener {

    // address of proxy object
    long __swiftObject;

    SwiftHelloTest_TestListenerProxy( long __swiftObject ) {
        this.__swiftObject = __swiftObject;
    }

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.setLoopback(com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener)

    public native void __setLoopback( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener loopback );

    public void setLoopback( com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener loopback ) {
        __setLoopback( __swiftObject, loopback );
    }

    /// public abstract boolean com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.booleanMethod(boolean)

    public native boolean __booleanMethod( long __swiftObject, boolean arg );

    public boolean booleanMethod( boolean arg ) {
        return __booleanMethod( __swiftObject, arg );
    }

    /// public abstract boolean[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.booleanArrayMethod(boolean[])

    public native boolean[] __booleanArrayMethod( long __swiftObject, boolean[] arg );

    public boolean[] booleanArrayMethod( boolean[] arg ) {
        return __booleanArrayMethod( __swiftObject, arg );
    }

    /// public abstract boolean[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.boolean2dArrayMethod(boolean[][])

    public native boolean[][] __boolean2dArrayMethod( long __swiftObject, boolean[][] arg );

    public boolean[][] boolean2dArrayMethod( boolean[][] arg ) {
        return __boolean2dArrayMethod( __swiftObject, arg );
    }

    /// public abstract byte com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.byteMethod(byte)

    public native byte __byteMethod( long __swiftObject, byte arg );

    public byte byteMethod( byte arg ) {
        return __byteMethod( __swiftObject, arg );
    }

    /// public abstract byte[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.byteArrayMethod(byte[])

    public native byte[] __byteArrayMethod( long __swiftObject, byte[] arg );

    public byte[] byteArrayMethod( byte[] arg ) {
        return __byteArrayMethod( __swiftObject, arg );
    }

    /// public abstract byte[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.byte2dArrayMethod(byte[][])

    public native byte[][] __byte2dArrayMethod( long __swiftObject, byte[][] arg );

    public byte[][] byte2dArrayMethod( byte[][] arg ) {
        return __byte2dArrayMethod( __swiftObject, arg );
    }

    /// public abstract char com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.charMethod(char)

    public native char __charMethod( long __swiftObject, char arg );

    public char charMethod( char arg ) {
        return __charMethod( __swiftObject, arg );
    }

    /// public abstract char[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.charArrayMethod(char[])

    public native char[] __charArrayMethod( long __swiftObject, char[] arg );

    public char[] charArrayMethod( char[] arg ) {
        return __charArrayMethod( __swiftObject, arg );
    }

    /// public abstract char[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.char2dArrayMethod(char[][])

    public native char[][] __char2dArrayMethod( long __swiftObject, char[][] arg );

    public char[][] char2dArrayMethod( char[][] arg ) {
        return __char2dArrayMethod( __swiftObject, arg );
    }

    /// public abstract short com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.shortMethod(short)

    public native short __shortMethod( long __swiftObject, short arg );

    public short shortMethod( short arg ) {
        return __shortMethod( __swiftObject, arg );
    }

    /// public abstract short[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.shortArrayMethod(short[])

    public native short[] __shortArrayMethod( long __swiftObject, short[] arg );

    public short[] shortArrayMethod( short[] arg ) {
        return __shortArrayMethod( __swiftObject, arg );
    }

    /// public abstract short[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.short2dArrayMethod(short[][])

    public native short[][] __short2dArrayMethod( long __swiftObject, short[][] arg );

    public short[][] short2dArrayMethod( short[][] arg ) {
        return __short2dArrayMethod( __swiftObject, arg );
    }

    /// public abstract int com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.intMethod(int)

    public native int __intMethod( long __swiftObject, int arg );

    public int intMethod( int arg ) {
        return __intMethod( __swiftObject, arg );
    }

    /// public abstract int[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.intArrayMethod(int[])

    public native int[] __intArrayMethod( long __swiftObject, int[] arg );

    public int[] intArrayMethod( int[] arg ) {
        return __intArrayMethod( __swiftObject, arg );
    }

    /// public abstract int[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.int2dArrayMethod(int[][])

    public native int[][] __int2dArrayMethod( long __swiftObject, int[][] arg );

    public int[][] int2dArrayMethod( int[][] arg ) {
        return __int2dArrayMethod( __swiftObject, arg );
    }

    /// public abstract long com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.longMethod(long)

    public native long __longMethod( long __swiftObject, long arg );

    public long longMethod( long arg ) {
        return __longMethod( __swiftObject, arg );
    }

    /// public abstract long[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.longArrayMethod(long[])

    public native long[] __longArrayMethod( long __swiftObject, long[] arg );

    public long[] longArrayMethod( long[] arg ) {
        return __longArrayMethod( __swiftObject, arg );
    }

    /// public abstract long[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.long2dArrayMethod(long[][])

    public native long[][] __long2dArrayMethod( long __swiftObject, long[][] arg );

    public long[][] long2dArrayMethod( long[][] arg ) {
        return __long2dArrayMethod( __swiftObject, arg );
    }

    /// public abstract float com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.floatMethod(float)

    public native float __floatMethod( long __swiftObject, float arg );

    public float floatMethod( float arg ) {
        return __floatMethod( __swiftObject, arg );
    }

    /// public abstract float[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.floatArrayMethod(float[])

    public native float[] __floatArrayMethod( long __swiftObject, float[] arg );

    public float[] floatArrayMethod( float[] arg ) {
        return __floatArrayMethod( __swiftObject, arg );
    }

    /// public abstract float[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.float2dArrayMethod(float[][])

    public native float[][] __float2dArrayMethod( long __swiftObject, float[][] arg );

    public float[][] float2dArrayMethod( float[][] arg ) {
        return __float2dArrayMethod( __swiftObject, arg );
    }

    /// public abstract double com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.doubleMethod(double)

    public native double __doubleMethod( long __swiftObject, double arg );

    public double doubleMethod( double arg ) {
        return __doubleMethod( __swiftObject, arg );
    }

    /// public abstract double[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.doubleArrayMethod(double[])

    public native double[] __doubleArrayMethod( long __swiftObject, double[] arg );

    public double[] doubleArrayMethod( double[] arg ) {
        return __doubleArrayMethod( __swiftObject, arg );
    }

    /// public abstract double[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.double2dArrayMethod(double[][])

    public native double[][] __double2dArrayMethod( long __swiftObject, double[][] arg );

    public double[][] double2dArrayMethod( double[][] arg ) {
        return __double2dArrayMethod( __swiftObject, arg );
    }

    /// public abstract java.lang.String com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.StringMethod(java.lang.String)

    public native java.lang.String __StringMethod( long __swiftObject, java.lang.String arg );

    public java.lang.String StringMethod( java.lang.String arg ) {
        return __StringMethod( __swiftObject, arg );
    }

    /// public abstract java.lang.String[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.StringArrayMethod(java.lang.String[])

    public native java.lang.String[] __StringArrayMethod( long __swiftObject, java.lang.String[] arg );

    public java.lang.String[] StringArrayMethod( java.lang.String[] arg ) {
        return __StringArrayMethod( __swiftObject, arg );
    }

    /// public abstract java.lang.String[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.String2dArrayMethod(java.lang.String[][])

    public native java.lang.String[][] __String2dArrayMethod( long __swiftObject, java.lang.String[][] arg );

    public java.lang.String[][] String2dArrayMethod( java.lang.String[][] arg ) {
        return __String2dArrayMethod( __swiftObject, arg );
    }

    /// public abstract com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.TestListenerMethod(com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener)

    public native com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener __TestListenerMethod( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener arg );

    public com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener TestListenerMethod( com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener arg ) {
        return __TestListenerMethod( __swiftObject, arg );
    }

    /// public abstract com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.TestListenerArrayMethod(com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener[])

    public native com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[] __TestListenerArrayMethod( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[] arg );

    public com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[] TestListenerArrayMethod( com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[] arg ) {
        return __TestListenerArrayMethod( __swiftObject, arg );
    }

    /// public abstract com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.TestListener2dArrayMethod(com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener[][])

    public native com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[][] __TestListener2dArrayMethod( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[][] arg );

    public com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[][] TestListener2dArrayMethod( com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[][] arg ) {
        return __TestListener2dArrayMethod( __swiftObject, arg );
    }

    /// public abstract com.johnholdsworth.swiftbindings.SwiftHelloTypes$ListenerMap com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.testMap(com.johnholdsworth.swiftbindings.SwiftHelloTypes$ListenerMap)

    public native com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMap __testMap( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMap arg );

    public com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMap testMap( com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMap arg ) {
        return __testMap( __swiftObject, arg );
    }

    /// public abstract com.johnholdsworth.swiftbindings.SwiftHelloTypes$ListenerMapList com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener.testMapList(com.johnholdsworth.swiftbindings.SwiftHelloTypes$ListenerMapList)

    public native com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMapList __testMapList( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMapList arg );

    public com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMapList testMapList( com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMapList arg ) {
        return __testMapList( __swiftObject, arg );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
