
/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter ///

package org.swiftjava.com_johnholdsworth;

@SuppressWarnings("JniMissingFunction")
public class SwiftHelloTest_TestResponderAdapterProxy extends com.johnholdsworth.swiftbindings.SwiftHelloTest.TestResponderAdapter {

    // address of proxy object
    long __swiftObject;

    /// public com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter()

    SwiftHelloTest_TestResponderAdapterProxy( long __swiftObject ) {
        super( );
        this.__swiftObject = __swiftObject;
    }

    /// public java.lang.String[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.String2dArrayMethod(java.lang.String[][])

    public native java.lang.String[][] __String2dArrayMethod( long __swiftObject, java.lang.String[][] arg );

    boolean entered_String2dArrayMethod_0;

    public java.lang.String[][] String2dArrayMethod( java.lang.String[][] arg ) {
        if ( !entered_String2dArrayMethod_0 ) {
            entered_String2dArrayMethod_0 = true;
            java.lang.String[][] __return = __String2dArrayMethod( __swiftObject, arg);
            entered_String2dArrayMethod_0 = false;
            return __return;
        }
        else
            return super.String2dArrayMethod( arg );
    }

    /// public java.lang.String[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.StringArrayMethod(java.lang.String[])

    public native java.lang.String[] __StringArrayMethod( long __swiftObject, java.lang.String[] arg );

    boolean entered_StringArrayMethod_1;

    public java.lang.String[] StringArrayMethod( java.lang.String[] arg ) {
        if ( !entered_StringArrayMethod_1 ) {
            entered_StringArrayMethod_1 = true;
            java.lang.String[] __return = __StringArrayMethod( __swiftObject, arg);
            entered_StringArrayMethod_1 = false;
            return __return;
        }
        else
            return super.StringArrayMethod( arg );
    }

    /// public java.lang.String com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.StringMethod(java.lang.String)

    public native java.lang.String __StringMethod( long __swiftObject, java.lang.String arg );

    boolean entered_StringMethod_2;

    public java.lang.String StringMethod( java.lang.String arg ) {
        if ( !entered_StringMethod_2 ) {
            entered_StringMethod_2 = true;
            java.lang.String __return = __StringMethod( __swiftObject, arg);
            entered_StringMethod_2 = false;
            return __return;
        }
        else
            return super.StringMethod( arg );
    }

    /// public com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.TestListener2dArrayMethod(com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener[][])

    public native com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[][] __TestListener2dArrayMethod( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[][] arg );

    boolean entered_TestListener2dArrayMethod_3;

    public com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[][] TestListener2dArrayMethod( com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[][] arg ) {
        if ( !entered_TestListener2dArrayMethod_3 ) {
            entered_TestListener2dArrayMethod_3 = true;
            com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[][] __return = __TestListener2dArrayMethod( __swiftObject, arg);
            entered_TestListener2dArrayMethod_3 = false;
            return __return;
        }
        else
            return super.TestListener2dArrayMethod( arg );
    }

    /// public com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.TestListenerArrayMethod(com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener[])

    public native com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[] __TestListenerArrayMethod( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[] arg );

    boolean entered_TestListenerArrayMethod_4;

    public com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[] TestListenerArrayMethod( com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[] arg ) {
        if ( !entered_TestListenerArrayMethod_4 ) {
            entered_TestListenerArrayMethod_4 = true;
            com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener[] __return = __TestListenerArrayMethod( __swiftObject, arg);
            entered_TestListenerArrayMethod_4 = false;
            return __return;
        }
        else
            return super.TestListenerArrayMethod( arg );
    }

    /// public com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.TestListenerMethod(com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener)

    public native com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener __TestListenerMethod( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener arg );

    boolean entered_TestListenerMethod_5;

    public com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener TestListenerMethod( com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener arg ) {
        if ( !entered_TestListenerMethod_5 ) {
            entered_TestListenerMethod_5 = true;
            com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener __return = __TestListenerMethod( __swiftObject, arg);
            entered_TestListenerMethod_5 = false;
            return __return;
        }
        else
            return super.TestListenerMethod( arg );
    }

    /// public boolean[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.boolean2dArrayMethod(boolean[][])

    public native boolean[][] __boolean2dArrayMethod( long __swiftObject, boolean[][] arg );

    boolean entered_boolean2dArrayMethod_6;

    public boolean[][] boolean2dArrayMethod( boolean[][] arg ) {
        if ( !entered_boolean2dArrayMethod_6 ) {
            entered_boolean2dArrayMethod_6 = true;
            boolean[][] __return = __boolean2dArrayMethod( __swiftObject, arg);
            entered_boolean2dArrayMethod_6 = false;
            return __return;
        }
        else
            return super.boolean2dArrayMethod( arg );
    }

    /// public boolean[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.booleanArrayMethod(boolean[])

    public native boolean[] __booleanArrayMethod( long __swiftObject, boolean[] arg );

    boolean entered_booleanArrayMethod_7;

    public boolean[] booleanArrayMethod( boolean[] arg ) {
        if ( !entered_booleanArrayMethod_7 ) {
            entered_booleanArrayMethod_7 = true;
            boolean[] __return = __booleanArrayMethod( __swiftObject, arg);
            entered_booleanArrayMethod_7 = false;
            return __return;
        }
        else
            return super.booleanArrayMethod( arg );
    }

    /// public boolean com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.booleanMethod(boolean)

    public native boolean __booleanMethod( long __swiftObject, boolean arg );

    boolean entered_booleanMethod_8;

    public boolean booleanMethod( boolean arg ) {
        if ( !entered_booleanMethod_8 ) {
            entered_booleanMethod_8 = true;
            boolean __return = __booleanMethod( __swiftObject, arg);
            entered_booleanMethod_8 = false;
            return __return;
        }
        else
            return super.booleanMethod( arg );
    }

    /// public byte[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.byte2dArrayMethod(byte[][])

    public native byte[][] __byte2dArrayMethod( long __swiftObject, byte[][] arg );

    boolean entered_byte2dArrayMethod_9;

    public byte[][] byte2dArrayMethod( byte[][] arg ) {
        if ( !entered_byte2dArrayMethod_9 ) {
            entered_byte2dArrayMethod_9 = true;
            byte[][] __return = __byte2dArrayMethod( __swiftObject, arg);
            entered_byte2dArrayMethod_9 = false;
            return __return;
        }
        else
            return super.byte2dArrayMethod( arg );
    }

    /// public byte[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.byteArrayMethod(byte[])

    public native byte[] __byteArrayMethod( long __swiftObject, byte[] arg );

    boolean entered_byteArrayMethod_10;

    public byte[] byteArrayMethod( byte[] arg ) {
        if ( !entered_byteArrayMethod_10 ) {
            entered_byteArrayMethod_10 = true;
            byte[] __return = __byteArrayMethod( __swiftObject, arg);
            entered_byteArrayMethod_10 = false;
            return __return;
        }
        else
            return super.byteArrayMethod( arg );
    }

    /// public byte com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.byteMethod(byte)

    public native byte __byteMethod( long __swiftObject, byte arg );

    boolean entered_byteMethod_11;

    public byte byteMethod( byte arg ) {
        if ( !entered_byteMethod_11 ) {
            entered_byteMethod_11 = true;
            byte __return = __byteMethod( __swiftObject, arg);
            entered_byteMethod_11 = false;
            return __return;
        }
        else
            return super.byteMethod( arg );
    }

    /// public char[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.char2dArrayMethod(char[][])

    public native char[][] __char2dArrayMethod( long __swiftObject, char[][] arg );

    boolean entered_char2dArrayMethod_12;

    public char[][] char2dArrayMethod( char[][] arg ) {
        if ( !entered_char2dArrayMethod_12 ) {
            entered_char2dArrayMethod_12 = true;
            char[][] __return = __char2dArrayMethod( __swiftObject, arg);
            entered_char2dArrayMethod_12 = false;
            return __return;
        }
        else
            return super.char2dArrayMethod( arg );
    }

    /// public char[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.charArrayMethod(char[])

    public native char[] __charArrayMethod( long __swiftObject, char[] arg );

    boolean entered_charArrayMethod_13;

    public char[] charArrayMethod( char[] arg ) {
        if ( !entered_charArrayMethod_13 ) {
            entered_charArrayMethod_13 = true;
            char[] __return = __charArrayMethod( __swiftObject, arg);
            entered_charArrayMethod_13 = false;
            return __return;
        }
        else
            return super.charArrayMethod( arg );
    }

    /// public char com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.charMethod(char)

    public native char __charMethod( long __swiftObject, char arg );

    boolean entered_charMethod_14;

    public char charMethod( char arg ) {
        if ( !entered_charMethod_14 ) {
            entered_charMethod_14 = true;
            char __return = __charMethod( __swiftObject, arg);
            entered_charMethod_14 = false;
            return __return;
        }
        else
            return super.charMethod( arg );
    }

    /// public double[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.double2dArrayMethod(double[][])

    public native double[][] __double2dArrayMethod( long __swiftObject, double[][] arg );

    boolean entered_double2dArrayMethod_15;

    public double[][] double2dArrayMethod( double[][] arg ) {
        if ( !entered_double2dArrayMethod_15 ) {
            entered_double2dArrayMethod_15 = true;
            double[][] __return = __double2dArrayMethod( __swiftObject, arg);
            entered_double2dArrayMethod_15 = false;
            return __return;
        }
        else
            return super.double2dArrayMethod( arg );
    }

    /// public double[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.doubleArrayMethod(double[])

    public native double[] __doubleArrayMethod( long __swiftObject, double[] arg );

    boolean entered_doubleArrayMethod_16;

    public double[] doubleArrayMethod( double[] arg ) {
        if ( !entered_doubleArrayMethod_16 ) {
            entered_doubleArrayMethod_16 = true;
            double[] __return = __doubleArrayMethod( __swiftObject, arg);
            entered_doubleArrayMethod_16 = false;
            return __return;
        }
        else
            return super.doubleArrayMethod( arg );
    }

    /// public double com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.doubleMethod(double)

    public native double __doubleMethod( long __swiftObject, double arg );

    boolean entered_doubleMethod_17;

    public double doubleMethod( double arg ) {
        if ( !entered_doubleMethod_17 ) {
            entered_doubleMethod_17 = true;
            double __return = __doubleMethod( __swiftObject, arg);
            entered_doubleMethod_17 = false;
            return __return;
        }
        else
            return super.doubleMethod( arg );
    }

    /// public boolean java.lang.Object.equals(java.lang.Object)

    public native boolean __equals( long __swiftObject, java.lang.Object arg0 );

    boolean entered_equals_18;

    public boolean equals( java.lang.Object arg0 ) {
        if ( !entered_equals_18 ) {
            entered_equals_18 = true;
            boolean __return = __equals( __swiftObject, arg0);
            entered_equals_18 = false;
            return __return;
        }
        else
            return super.equals( arg0 );
    }

    /// public float[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.float2dArrayMethod(float[][])

    public native float[][] __float2dArrayMethod( long __swiftObject, float[][] arg );

    boolean entered_float2dArrayMethod_19;

    public float[][] float2dArrayMethod( float[][] arg ) {
        if ( !entered_float2dArrayMethod_19 ) {
            entered_float2dArrayMethod_19 = true;
            float[][] __return = __float2dArrayMethod( __swiftObject, arg);
            entered_float2dArrayMethod_19 = false;
            return __return;
        }
        else
            return super.float2dArrayMethod( arg );
    }

    /// public float[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.floatArrayMethod(float[])

    public native float[] __floatArrayMethod( long __swiftObject, float[] arg );

    boolean entered_floatArrayMethod_20;

    public float[] floatArrayMethod( float[] arg ) {
        if ( !entered_floatArrayMethod_20 ) {
            entered_floatArrayMethod_20 = true;
            float[] __return = __floatArrayMethod( __swiftObject, arg);
            entered_floatArrayMethod_20 = false;
            return __return;
        }
        else
            return super.floatArrayMethod( arg );
    }

    /// public float com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.floatMethod(float)

    public native float __floatMethod( long __swiftObject, float arg );

    boolean entered_floatMethod_21;

    public float floatMethod( float arg ) {
        if ( !entered_floatMethod_21 ) {
            entered_floatMethod_21 = true;
            float __return = __floatMethod( __swiftObject, arg);
            entered_floatMethod_21 = false;
            return __return;
        }
        else
            return super.floatMethod( arg );
    }

    /// public native int java.lang.Object.hashCode()

    public native int __hashCode( long __swiftObject );

    boolean entered_hashCode_22;

    public int hashCode() {
        if ( !entered_hashCode_22 ) {
            entered_hashCode_22 = true;
            int __return = __hashCode( __swiftObject );
            entered_hashCode_22 = false;
            return __return;
        }
        else
            return super.hashCode( );
    }

    /// public int[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.int2dArrayMethod(int[][])

    public native int[][] __int2dArrayMethod( long __swiftObject, int[][] arg );

    boolean entered_int2dArrayMethod_23;

    public int[][] int2dArrayMethod( int[][] arg ) {
        if ( !entered_int2dArrayMethod_23 ) {
            entered_int2dArrayMethod_23 = true;
            int[][] __return = __int2dArrayMethod( __swiftObject, arg);
            entered_int2dArrayMethod_23 = false;
            return __return;
        }
        else
            return super.int2dArrayMethod( arg );
    }

    /// public int[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.intArrayMethod(int[])

    public native int[] __intArrayMethod( long __swiftObject, int[] arg );

    boolean entered_intArrayMethod_24;

    public int[] intArrayMethod( int[] arg ) {
        if ( !entered_intArrayMethod_24 ) {
            entered_intArrayMethod_24 = true;
            int[] __return = __intArrayMethod( __swiftObject, arg);
            entered_intArrayMethod_24 = false;
            return __return;
        }
        else
            return super.intArrayMethod( arg );
    }

    /// public int com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.intMethod(int)

    public native int __intMethod( long __swiftObject, int arg );

    boolean entered_intMethod_25;

    public int intMethod( int arg ) {
        if ( !entered_intMethod_25 ) {
            entered_intMethod_25 = true;
            int __return = __intMethod( __swiftObject, arg);
            entered_intMethod_25 = false;
            return __return;
        }
        else
            return super.intMethod( arg );
    }

    /// public long[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.long2dArrayMethod(long[][])

    public native long[][] __long2dArrayMethod( long __swiftObject, long[][] arg );

    boolean entered_long2dArrayMethod_26;

    public long[][] long2dArrayMethod( long[][] arg ) {
        if ( !entered_long2dArrayMethod_26 ) {
            entered_long2dArrayMethod_26 = true;
            long[][] __return = __long2dArrayMethod( __swiftObject, arg);
            entered_long2dArrayMethod_26 = false;
            return __return;
        }
        else
            return super.long2dArrayMethod( arg );
    }

    /// public long[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.longArrayMethod(long[])

    public native long[] __longArrayMethod( long __swiftObject, long[] arg );

    boolean entered_longArrayMethod_27;

    public long[] longArrayMethod( long[] arg ) {
        if ( !entered_longArrayMethod_27 ) {
            entered_longArrayMethod_27 = true;
            long[] __return = __longArrayMethod( __swiftObject, arg);
            entered_longArrayMethod_27 = false;
            return __return;
        }
        else
            return super.longArrayMethod( arg );
    }

    /// public long com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.longMethod(long)

    public native long __longMethod( long __swiftObject, long arg );

    boolean entered_longMethod_28;

    public long longMethod( long arg ) {
        if ( !entered_longMethod_28 ) {
            entered_longMethod_28 = true;
            long __return = __longMethod( __swiftObject, arg);
            entered_longMethod_28 = false;
            return __return;
        }
        else
            return super.longMethod( arg );
    }

    /// public void com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.setLoopback(com.johnholdsworth.swiftbindings.SwiftHelloTest$TestListener)

    public native void __setLoopback( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener loopback );

    boolean entered_setLoopback_29;

    public void setLoopback( com.johnholdsworth.swiftbindings.SwiftHelloTest.TestListener loopback ) {
        if ( !entered_setLoopback_29 ) {
            entered_setLoopback_29 = true;
            __setLoopback( __swiftObject, loopback);
            entered_setLoopback_29 = false;
        }
        else
            super.setLoopback( loopback );
    }

    /// public short[][] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.short2dArrayMethod(short[][])

    public native short[][] __short2dArrayMethod( long __swiftObject, short[][] arg );

    boolean entered_short2dArrayMethod_30;

    public short[][] short2dArrayMethod( short[][] arg ) {
        if ( !entered_short2dArrayMethod_30 ) {
            entered_short2dArrayMethod_30 = true;
            short[][] __return = __short2dArrayMethod( __swiftObject, arg);
            entered_short2dArrayMethod_30 = false;
            return __return;
        }
        else
            return super.short2dArrayMethod( arg );
    }

    /// public short[] com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.shortArrayMethod(short[])

    public native short[] __shortArrayMethod( long __swiftObject, short[] arg );

    boolean entered_shortArrayMethod_31;

    public short[] shortArrayMethod( short[] arg ) {
        if ( !entered_shortArrayMethod_31 ) {
            entered_shortArrayMethod_31 = true;
            short[] __return = __shortArrayMethod( __swiftObject, arg);
            entered_shortArrayMethod_31 = false;
            return __return;
        }
        else
            return super.shortArrayMethod( arg );
    }

    /// public short com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.shortMethod(short)

    public native short __shortMethod( long __swiftObject, short arg );

    boolean entered_shortMethod_32;

    public short shortMethod( short arg ) {
        if ( !entered_shortMethod_32 ) {
            entered_shortMethod_32 = true;
            short __return = __shortMethod( __swiftObject, arg);
            entered_shortMethod_32 = false;
            return __return;
        }
        else
            return super.shortMethod( arg );
    }

    /// public com.johnholdsworth.swiftbindings.SwiftHelloTypes$ListenerMap com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.testMap(com.johnholdsworth.swiftbindings.SwiftHelloTypes$ListenerMap)

    public native com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMap __testMap( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMap arg );

    boolean entered_testMap_33;

    public com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMap testMap( com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMap arg ) {
        if ( !entered_testMap_33 ) {
            entered_testMap_33 = true;
            com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMap __return = __testMap( __swiftObject, arg);
            entered_testMap_33 = false;
            return __return;
        }
        else
            return super.testMap( arg );
    }

    /// public com.johnholdsworth.swiftbindings.SwiftHelloTypes$ListenerMapList com.johnholdsworth.swiftbindings.SwiftHelloTest$TestResponderAdapter.testMapList(com.johnholdsworth.swiftbindings.SwiftHelloTypes$ListenerMapList)

    public native com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMapList __testMapList( long __swiftObject, com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMapList arg );

    boolean entered_testMapList_34;

    public com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMapList testMapList( com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMapList arg ) {
        if ( !entered_testMapList_34 ) {
            entered_testMapList_34 = true;
            com.johnholdsworth.swiftbindings.SwiftHelloTypes.ListenerMapList __return = __testMapList( __swiftObject, arg);
            entered_testMapList_34 = false;
            return __return;
        }
        else
            return super.testMapList( arg );
    }

    /// public java.lang.String java.lang.Object.toString()

    public native java.lang.String __toString( long __swiftObject );

    boolean entered_toString_35;

    public java.lang.String toString() {
        if ( !entered_toString_35 ) {
            entered_toString_35 = true;
            java.lang.String __return = __toString( __swiftObject );
            entered_toString_35 = false;
            return __return;
        }
        else
            return super.toString( );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
