
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface com.johnholdsworth.bindings.SwiftHelloTypes ///

public protocol SwiftHelloTypes: JavaProtocol {

}


open class SwiftHelloTypesForward: JNIObjectForward, SwiftHelloTypes {

    private static var SwiftHelloTypesJNIClass: jclass?

}


