
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface com.johnholdsworth.bindings.SwiftHelloBinding ///

public protocol SwiftHelloBinding: JavaProtocol {

}


open class SwiftHelloBindingForward: JNIObjectForward, SwiftHelloBinding {

    private static var SwiftHelloBindingJNIClass: jclass?

}


