
/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface javax.swing.event.TableModelListener ///

package org.swiftjava.javax_swing;

@SuppressWarnings("JniMissingFunction")
public class TableModelListenerProxy implements javax.swing.event.TableModelListener {

    // address of proxy object
    long __swiftObject;

    TableModelListenerProxy( long __swiftObject ) {
        this.__swiftObject = __swiftObject;
    }

    /// public abstract void javax.swing.event.TableModelListener.tableChanged(javax.swing.event.TableModelEvent)

    public native void __tableChanged( long __swiftObject, javax.swing.event.TableModelEvent e );

    public void tableChanged( javax.swing.event.TableModelEvent e ) {
        __tableChanged( __swiftObject, e );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
