
/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.awt.dnd.DropTargetAdapter ///

package org.swiftjava.java_awt;

@SuppressWarnings("JniMissingFunction")
public class DropTargetAdapterProxy extends java.awt.dnd.DropTargetAdapter {

    // address of proxy object
    long __swiftObject;

    /// public java.awt.dnd.DropTargetAdapter()

    DropTargetAdapterProxy( long __swiftObject ) {
        super( );
        this.__swiftObject = __swiftObject;
    }

    /// public void java.awt.dnd.DropTargetAdapter.dragEnter(java.awt.dnd.DropTargetDragEvent)

    public native void __dragEnter( long __swiftObject, java.awt.dnd.DropTargetDragEvent dtde );

    boolean entered_dragEnter_0;

    public void dragEnter( java.awt.dnd.DropTargetDragEvent dtde ) {
        if ( !entered_dragEnter_0 ) {
            entered_dragEnter_0 = true;
            __dragEnter( __swiftObject, dtde);
            entered_dragEnter_0 = false;
        }
        else
            super.dragEnter( dtde );
    }

    /// public void java.awt.dnd.DropTargetAdapter.dragExit(java.awt.dnd.DropTargetEvent)

    public native void __dragExit( long __swiftObject, java.awt.dnd.DropTargetEvent dte );

    boolean entered_dragExit_1;

    public void dragExit( java.awt.dnd.DropTargetEvent dte ) {
        if ( !entered_dragExit_1 ) {
            entered_dragExit_1 = true;
            __dragExit( __swiftObject, dte);
            entered_dragExit_1 = false;
        }
        else
            super.dragExit( dte );
    }

    /// public void java.awt.dnd.DropTargetAdapter.dragOver(java.awt.dnd.DropTargetDragEvent)

    public native void __dragOver( long __swiftObject, java.awt.dnd.DropTargetDragEvent dtde );

    boolean entered_dragOver_2;

    public void dragOver( java.awt.dnd.DropTargetDragEvent dtde ) {
        if ( !entered_dragOver_2 ) {
            entered_dragOver_2 = true;
            __dragOver( __swiftObject, dtde);
            entered_dragOver_2 = false;
        }
        else
            super.dragOver( dtde );
    }

    /// public abstract void java.awt.dnd.DropTargetListener.drop(java.awt.dnd.DropTargetDropEvent)

    public native void __drop( long __swiftObject, java.awt.dnd.DropTargetDropEvent dtde );

    boolean entered_drop_3;

    public void drop( java.awt.dnd.DropTargetDropEvent dtde ) {
        __drop( __swiftObject, dtde );
    }

    /// public void java.awt.dnd.DropTargetAdapter.dropActionChanged(java.awt.dnd.DropTargetDragEvent)

    public native void __dropActionChanged( long __swiftObject, java.awt.dnd.DropTargetDragEvent dtde );

    boolean entered_dropActionChanged_4;

    public void dropActionChanged( java.awt.dnd.DropTargetDragEvent dtde ) {
        if ( !entered_dropActionChanged_4 ) {
            entered_dropActionChanged_4 = true;
            __dropActionChanged( __swiftObject, dtde);
            entered_dropActionChanged_4 = false;
        }
        else
            super.dropActionChanged( dtde );
    }

    /// public boolean java.lang.Object.equals(java.lang.Object)

    public native boolean __equals( long __swiftObject, java.lang.Object arg0 );

    boolean entered_equals_5;

    public boolean equals( java.lang.Object arg0 ) {
        if ( !entered_equals_5 ) {
            entered_equals_5 = true;
            boolean __return = __equals( __swiftObject, arg0);
            entered_equals_5 = false;
            return __return;
        }
        else
            return super.equals( arg0 );
    }

    /// public native int java.lang.Object.hashCode()

    public native int __hashCode( long __swiftObject );

    boolean entered_hashCode_6;

    public int hashCode() {
        if ( !entered_hashCode_6 ) {
            entered_hashCode_6 = true;
            int __return = __hashCode( __swiftObject );
            entered_hashCode_6 = false;
            return __return;
        }
        else
            return super.hashCode( );
    }

    /// public java.lang.String java.lang.Object.toString()

    public native java.lang.String __toString( long __swiftObject );

    boolean entered_toString_7;

    public java.lang.String toString() {
        if ( !entered_toString_7 ) {
            entered_toString_7 = true;
            java.lang.String __return = __toString( __swiftObject );
            entered_toString_7 = false;
            return __return;
        }
        else
            return super.toString( );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
