
/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.awt.event.KeyAdapter ///

package org.swiftjava.java_awt;

@SuppressWarnings("JniMissingFunction")
public class KeyAdapterProxy extends java.awt.event.KeyAdapter {

    // address of proxy object
    long __swiftObject;

    /// public java.awt.event.KeyAdapter()

    KeyAdapterProxy( long __swiftObject ) {
        super( );
        this.__swiftObject = __swiftObject;
    }

    /// public boolean java.lang.Object.equals(java.lang.Object)

    public native boolean __equals( long __swiftObject, java.lang.Object arg0 );

    boolean entered_equals_0;

    public boolean equals( java.lang.Object arg0 ) {
        if ( !entered_equals_0 ) {
            entered_equals_0 = true;
            boolean __return = __equals( __swiftObject, arg0);
            entered_equals_0 = false;
            return __return;
        }
        else
            return super.equals( arg0 );
    }

    /// public native int java.lang.Object.hashCode()

    public native int __hashCode( long __swiftObject );

    boolean entered_hashCode_1;

    public int hashCode() {
        if ( !entered_hashCode_1 ) {
            entered_hashCode_1 = true;
            int __return = __hashCode( __swiftObject );
            entered_hashCode_1 = false;
            return __return;
        }
        else
            return super.hashCode( );
    }

    /// public void java.awt.event.KeyAdapter.keyPressed(java.awt.event.KeyEvent)

    public native void __keyPressed( long __swiftObject, java.awt.event.KeyEvent e );

    boolean entered_keyPressed_2;

    public void keyPressed( java.awt.event.KeyEvent e ) {
        if ( !entered_keyPressed_2 ) {
            entered_keyPressed_2 = true;
            __keyPressed( __swiftObject, e);
            entered_keyPressed_2 = false;
        }
        else
            super.keyPressed( e );
    }

    /// public void java.awt.event.KeyAdapter.keyReleased(java.awt.event.KeyEvent)

    public native void __keyReleased( long __swiftObject, java.awt.event.KeyEvent e );

    boolean entered_keyReleased_3;

    public void keyReleased( java.awt.event.KeyEvent e ) {
        if ( !entered_keyReleased_3 ) {
            entered_keyReleased_3 = true;
            __keyReleased( __swiftObject, e);
            entered_keyReleased_3 = false;
        }
        else
            super.keyReleased( e );
    }

    /// public void java.awt.event.KeyAdapter.keyTyped(java.awt.event.KeyEvent)

    public native void __keyTyped( long __swiftObject, java.awt.event.KeyEvent e );

    boolean entered_keyTyped_4;

    public void keyTyped( java.awt.event.KeyEvent e ) {
        if ( !entered_keyTyped_4 ) {
            entered_keyTyped_4 = true;
            __keyTyped( __swiftObject, e);
            entered_keyTyped_4 = false;
        }
        else
            super.keyTyped( e );
    }

    /// public java.lang.String java.lang.Object.toString()

    public native java.lang.String __toString( long __swiftObject );

    boolean entered_toString_5;

    public java.lang.String toString() {
        if ( !entered_toString_5 ) {
            entered_toString_5 = true;
            java.lang.String __return = __toString( __swiftObject );
            entered_toString_5 = false;
            return __return;
        }
        else
            return super.toString( );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
