
/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.awt.Window ///

package org.swiftjava.java_awt;

@SuppressWarnings("JniMissingFunction")
public class WindowProxy extends java.awt.Window {

    // address of proxy object
    long __swiftObject;

    /// public java.awt.Window(java.awt.Frame)

    WindowProxy( java.awt.Frame arg0 , long __swiftObject ) {
        super( arg0 );
        this.__swiftObject = __swiftObject;
    }

    /// public java.awt.Window(java.awt.Window)

    WindowProxy( java.awt.Window arg0 , long __swiftObject ) {
        super( arg0 );
        this.__swiftObject = __swiftObject;
    }

    /// public java.awt.Window(java.awt.Window,java.awt.GraphicsConfiguration)

    WindowProxy( java.awt.Window arg0, java.awt.GraphicsConfiguration arg1 , long __swiftObject ) {
        super( arg0, arg1 );
        this.__swiftObject = __swiftObject;
    }

    /// java.awt.Window(java.awt.GraphicsConfiguration)

    /// java.awt.Window() throws java.awt.HeadlessException

    /// public void java.awt.Window.paint(java.awt.Graphics)

    public native void __paint( long __swiftObject, java.awt.Graphics arg0 );

    boolean entered_paint_0;

    public void paint( java.awt.Graphics arg0 ) {
        if ( !entered_paint_0 ) {
            entered_paint_0 = true;
            __paint( __swiftObject, arg0);
            entered_paint_0 = false;
        }
        else
            super.paint( arg0 );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
