
/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface java.util.EventListener ///

package org.swiftjava.java_util;

@SuppressWarnings("JniMissingFunction")
public class EventListenerProxy implements java.util.EventListener {

    // address of proxy object
    long __swiftObject;

    EventListenerProxy( long __swiftObject ) {
        this.__swiftObject = __swiftObject;
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
