
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home ///
/// Sat Jul 29 19:01:18 BST 2017 ///

/// interface com.jh.SwiftHelloBinding ///

public protocol SwiftHelloBinding: JavaProtocol {

}

open class SwiftHelloBindingForward: JNIObjectForward, SwiftHelloBinding {

    private static var SwiftHelloBindingJNIClass: jclass?

}


